baseurl = "http://thesecondbestpageintheuniverse.net"
title = "The Second Best Page in the Universe"
languageCode = "en-us"

enableRobotsTXT = true # Suggested, enable robots.txt file
googleAnalytics = "" # Optional, add tracking Id for analytics
SectionPagesMenu = "" # Enable menu system for lazy bloggers


[params]
  description = "Why you're wrong about everything." # Suggested, controls homepage description meta
  author = "" # Optional, controls author name display on posts
  show_menu = false # Optional, set false to disable menu entirely
  powered_by = false # Optional, set false to disable theme credits

  [params.seo]
    google_verify = "" # Optional, Google verification code
    bing_verify = "" # Optional, Bing verification code
    yandex_verify = "" # Optional, Yandex verification code
